### ISSUE TITLE
The arrow function have the parameter cannot be covered

### ISSUE THREAD

**Issue by caolei12daxia** [istanbuljs/babel-plugin-istanbul#114] opened 2017-06-15 03:18 UTC
`export const testConst = ({ test }) => test;`
`({ test }) => test; ` Statement not covered

`() => function(this).querySelector('[data-test-name="dataTestName"]')`
 #`querySelector('[data-test-name="dataTestName"]')` Statement not covered

**Comment by bcoe** [comment] 2017-07-22 20:18
@caolei12daxia as long as I exercise `testConst` in tests, I seem to get the coverage I would expect:

```js
export const testConst = ({ test }) => console.log(test)
testConst({test: 'batman'})
```

<img width="524" alt="screen shot 2017-07-22 at 1 17 49 pm" src="https://user-images.githubusercontent.com/194609/28494336-2f81a2a6-6ee0-11e7-9cd1-6c7c2aa3237c.png">

Can you provide a repo that reproduces the issue that you're bumping into?

**Comment by caolei12daxia** [comment] 2017-07-25 06:04
Hi @bcoe 
Sometimes you cannot call the function
`withContext(
    ({ children }) => ({
      __numberOfColumns__: getNumberOfColumns(children)
    })
  )`
this statement not to be covered.
`withContext(
    ({ }) => ({
      __numberOfColumns__: getNumberOfColumns(children)
    })
  )`
this statement is covered.
So I think the first code should be covered.

**Comment by bcoe** [comment] 2017-09-16 19:25
I'm a little confused, I'd expect ` ({ test }) => test` not to be covered until `testConst` is executed; this is how Istanbul works, it places counters around the statement which increment when it's executed.

If I'm missing something, could you provide a small example in a GitHub repo that you'd expect to be covered but fails?

**Comment by nelsyeung** [comment] 2017-12-27 18:22
I don't know whether this helps, but Jest uses this package and I have made repository that uses it which is similar to this problem, if not exactly the same. I've logged an issue there but they suggested to log an issue on here, you can find more information on https://github.com/facebook/jest/issues/5001.

**Comment by lukescott** [comment] 2018-01-03 18:56
From the linked issue it seems to be only happening with Babel 7. Babel 6 worked correctly. I'm observing this as well with my .map arrow funcs in my React render methods.

**Comment by coreyfarrell** [comment] 2020-11-29 15:11
If your tests never call an arrow function then it is not covered, being reported as such is correct.

I'm closing this issue as it is old and does not provide enough information to troubleshoot.  To look deeper we would need a minimal repository demonstrating the issue.  Preferably with no other transformations included to rule out compatibility issues with other transformations.

**Closed by coreyfarrell** 2020-11-29 15:11 UTC
Labels: triaged
