### ISSUE TITLE
Doesn't work with babel-plugin-rewire

### ISSUE THREAD

**Issue by tuckerconnelly** [istanbuljs/babel-plugin-istanbul#22] opened 2016-07-24 16:45 UTC
When I try to use this with babel-plugin-rewire, I get `Cannot read property 'start' of undefined`

**Comment by tuckerconnelly** [comment] 2016-07-27 19:25
Submitted PRs for this in [https://github.com/istanbuljs/istanbul-lib-instrument/pull/16](istanbul-lib-instrument) and [https://github.com/istanbuljs/istanbul-lib-coverage/pull/3](istanbul-lib-coverage)

**Comment by jseminck** [comment] 2016-08-12 08:12
This is now working for us as we had the same problem as OP. So this issue can probably be closed then.

**Comment by main-kun** [comment] 2016-08-13 00:16
Still doesn't work for me. In fact, in my case it was not working before on ubuntu server, but worked perfectly on my mac, but now I get the same error on mac too. Cleared the cache, deleted npm_modules and checked that babel-plugin-istanbul picked up the new versions.

**Comment by bcoe** [comment] 2016-08-14 02:03
@main-kun could you write a minimal reproduction, and share it with us; so that we can dig into the issue?

**Comment by main-kun** [comment] 2016-08-14 02:06
@bcoe sure, will do tomorrow

**Comment by main-kun** [comment] 2016-08-14 14:06
So, my environment: OS X El Capitan, karma +  webpack + jasmine in PhantomJS
babel-plugin-istanbul version 2.0.0
My .babelrc:
```
{
  "presets": ["es2015", "stage-0", "react"],
  "env": {
    "test": {
      "plugins": ["babel-plugin-rewire", "istanbul"]
    }
  }
}

```

I don't have Rewire in the code anymore, the error shows up just when starting the tests 

Karma output: 
```
14 08 2016 17:01:54.992:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#GNsMiJkikda4Hy1dAAAA with id 84596253
 PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 61 of 61 SUCCESS (0.349 secs / 0.315 secs)
.
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 61 of 61 SUCCESS (0.349 secs / 0.315 secs)
14 08 2016 17:01:56.287:ERROR [coverage]: [TypeError: Cannot read property 'start' of undefined]
TypeError: Cannot read property 'start' of undefined
    at /Users/me/Work/frontend/node_modules/istanbul/lib/object-utils.js:59:44
    at Array.forEach (native)
    at Object.addDerivedInfoForFile (/Users/me/Work/frontend/node_modules/istanbul/lib/object-utils.js:58:37)
    at Object.Collector.fileCoverageFor (/Users/me/Work/frontend/node_modules/istanbul/lib/collector.js:94:15)
    at /Users/me/Work/frontend/node_modules/istanbul/lib/report/html.js:558:90
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeReport (/Users/me/Work/frontend/node_modules/istanbul/lib/report/html.js:557:27)
    at writeReport (/Users/me/Work/frontend/node_modules/karma-coverage/lib/reporter.js:68:16)
    at /Users/me/Work/frontend/node_modules/karma-coverage/lib/reporter.js:296:11
    at /Users/me/Work/frontend/node_modules/karma/lib/helper.js:144:7
    at FSReqWrap.oncomplete (fs.js:82:15)


```

**Comment by jseminck** [comment] 2016-08-14 14:39
@main-kun I'm setting up an example project with `babel-plugin-rewire` and `babel-plugin-istanbul` to push to Github after my experience this week.

However I ran into the same issue as you have above.

I compared my test project against my working project and noticed the version of `babel-plugin-rewire` is `1.0.0-rc-5` - but my working project uses `1.0.0-rc-4`. I downgraded my test project to rc4 and the error went way. Can you try a downgrade and then try again?

I'll try to finish the setup today and put it on Github. Hopefully it can help to clarify what is the issue.

**Comment by main-kun** [comment] 2016-08-14 14:51
Yep, downgraded to rc-4 and the error is gone

**Comment by bcoe** [comment] 2016-08-16 20:34
@tuckerconnelly, @main-kun, @BenoitAverty, can we close this? or should we be opening an issue on babel-plugin-rewire?

**Comment by BenoitAverty** [comment] 2016-08-17 04:54
We should probably file an issue if this is still present in their rc-5. I'd also like to report that the same kind of problem is present in [istanbul-reports](https://github.com/istanbuljs/istanbul-reports/blob/master/lib/html/annotator.js#L137-L143). It doesn't make the reporter fail, but the error message is present in the html files instead of the code.

**Comment by jseminck** [comment] 2016-08-17 06:35
There is an existing issue, but it needs more information: https://github.com/speedskater/babel-plugin-rewire/issues/148

**Comment by jseminck** [comment] 2016-08-24 04:43
I have updated the issue on the `babel-rewire-plugin` page with an example project that works with `rc4` and not with `rc5`. 

The tricky thing is that the error is appearing in `istanbul` code. 

```js
24 08 2016 07:36:30.143:ERROR [coverage]: [TypeError: Cannot read property 'start' of undefined]
TypeError: Cannot read property 'start' of undefined
    at /Users/joachimseminck/Projects/karma-rewire-istanbul-example/node_modules/istanbul/lib/object-utils.js:59:44
```

See: https://github.com/gotwarlost/istanbul/blob/master/lib/object-utils.js#L59

The fix for istanbul side would be very simple and similar to what has been patched to the PRs related to this issue: https://github.com/istanbuljs/istanbul-lib-coverage/pull/3/commits/af55cf288dc097a41c26f1bca24952b3796a1e9c#diff-17dc9a452db5488b5cc544f82988d51bR169

However, the only variable that's changing here is the `babel-plugin-rewire` version...  

So I am not sure if we should make a PR to `istanbul` to fix this issue there, or if we should try and understand why `babel-plugin-rewire` produces different result between `rc4` and `rc5` first. I imagine that `istanbul` doesn't want to make fixes every release due to changes in `babel-plugin-rewire` that might break things?

**Comment by olabalboa** [comment] 2016-11-30 14:43
I'm having a similar problem when trying to integrate babel-plugin-rewire in a project based on react-boilerblate by @mxstbr.

It doesn't matter if I use `rc4` of babel-plugin-rewire, I still get the same error. I have forked react-boilerplate, bumped some dependencies, changed karma config to use PhantomJS and added babel-plugin-rewire. If someone would like to have a look the code is here https://github.com/olabalboa/react-boilerplate

```
30 11 2016 15:23:02.776:ERROR [coverage]: TypeError: Cannot read property 'start' of undefined
    at /home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:276:32
    at Array.forEach (native)
    at annotateBranches (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:255:30)
    at HtmlReport.writeDetailPage (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:426:9)
    at /home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:489:26
    at SyncFileWriter.writeFile (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.writeFile (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:488:24
    at Array.forEach (native)
    at HtmlReport.writeFiles (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:482:23)
    at /home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:484:22
    at Array.forEach (native)
    at HtmlReport.writeFiles (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:482:23)
    at HtmlReport.writeReport (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/html.js:566:14)
    at LcovReport.writeReport (/home/a168298/repos/react-boilerplate/node_modules/istanbul/lib/report/lcov.js:55:19)
    at writeReport (/home/a168298/repos/react-boilerplate/node_modules/karma-coverage/lib/reporter.js:68:16)
```

**Comment by bcoe** [comment] 2017-07-22 20:54
@tuckerconnelly this issue should now be addressed (with the caveat that the include order of babel-plugin-rewire, and babel-plugin-istanbul matters, see the documentation in babel-plugin-rewire on this topic).

Here's the issue where we fixed this bug: https://github.com/istanbuljs-archived-repos/istanbul-reports/pull/11

**Closed by bcoe** 2017-07-22 20:54 UTC
Labels: enhancement
