### ISSUE TITLE
plugin is sloooooooow compared to `__coverage__`:

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/babel-plugin-istanbul#5] opened 2016-06-28 17:00 UTC
see: https://github.com/dtinth/babel-plugin-__coverage__/issues/42

My hunch is maybe we're not caching the transforms? but let's crack up `v8-profile` and figure this out.

**Comment by dtinth** [comment] 2016-06-28 17:29
I don’t have time to do a proper profiling yet, but I can help clarify Babel’s caching behavior. Caching is done by `babel-core`, but by:

- [babel-node and babel-register](https://babeljs.io/docs/usage/require/#environment-variables)
- [babel-loader](https://github.com/babel/babel-loader)

As for caching heuristics, according to Babel loader,

> Default is a string composed by the babel-core's version, the babel-loader's version and the contents of .babelrc file if it exists. This can set to a custom value to force cache busting if the identifier changes.

This means caching should work out-of-the-box if you haven’t changed your `.babelrc` file. For `nyc`, I think it’s `babel-register` that’s being used. For me I used webpack, so it’s `babel-loader`’s cache (webpack also has its own in-memory cache).

**Comment by gotwarlost** [comment] 2016-06-28 18:27
Before we do too much profiling and such I want to rule out one possibility.

I noticed with the istanbul plugin, the babel generation time balloons by orders of magnitude when `compact` is not turned on.

```
$ time babel  --presets es2015 --plugins istanbul  <visitor.js >/dev/null
real	0m12.007s
user	0m12.087s
sys	0m0.106s

$ time babel --compact --presets es2015 --plugins istanbul  <visitor.js >/dev/null
real	0m1.350s
user	0m1.426s
sys	0m0.098s
```

OTOH the time difference in compact v/s non-compact for the `__coverage__` plugin is of the order of 0.5 seconds for the same file.

**Comment by hzoo** [comment] 2016-06-28 21:11
@dtinth yeah the caching is kind of broken is certain ways which is also why we don't "recommend" babel-register in production. (the cache is at `.babel.json` in your home directory)

`let cacheKey = `${JSON.stringify(opts)}:${babel.version}`;` - the babel version might not update but the other plugins might update the the key isn't correct in that case (might need to make a few fixes)

**Comment by gotwarlost** [comment] 2016-06-29 02:19
I believe I found the root cause. The `__coverage__` plugin creates a JSON string of the coverage data and does a runtime `JSON.parse` to populate the coverage object, The `istanbul` plugin creates a deep object expression and directly assigns to the coverage object - I wanted to avoid the overhead of  json parse at runtime.

The problem seems to be that when the coverage object is rendered by Babel in non-compact mode some non-linear formatting algorithm is taking ages to render it. The bigger the object, the exponentially slower the speed.

Let me put out a PR that uses `JSON.parse` instead and we can compare the performance.

**Comment by loganfsmyth** [comment] 2016-06-29 02:21
If you have a solid example of Babel's code generator being terrible, I'd be happy to investigate, since I've been optimizing it recently.

**Comment by gotwarlost** [comment] 2016-06-29 02:25
@loganfsmyth - let me provide a reproducible test case

**Comment by gotwarlost** [comment] 2016-06-29 03:39
@loganfsmyth - very simple test case that shows non-linear generator behavior when not in compact mode.

https://gist.github.com/gotwarlost/bca1c73e7a5135ad0d143d72db59fc40

**Comment by loganfsmyth** [comment] 2016-06-29 04:19
Appreciated, the core issue for this has been my next big TODO for the code generator's performance, unfortunately it's also not a small change so it's been going a bit slowly because the naive approach keeps causing our tests break because of small whitespace changes.

Basically at the moment the code generator ends up with a loop like this:
```
while (stuff){
    output += stuff

    if (output.match(conditions)){
     // stuff
    }
}
```

On its own, V8 handles repeated string concatenation well by treating a string as many tiny chunks, but because we attempt to then access the value (instead of it being write-only), we then force V8 to reallocate a contiguous block of memory to allow for fast random access and comparison. Ideally we'd treat the output as write-only and that would cause this to be dramatically faster.

On my branch incomplete with the fixes for this I get the following for your snippets:
```
// non-compact
Items: 2 , time: 6
Items: 4 , time: 2
Items: 8 , time: 4
Items: 16 , time: 5
Items: 32 , time: 5
Items: 64 , time: 8
Items: 128 , time: 7
Items: 256 , time: 12
Items: 512 , time: 28
Items: 1024 , time: 55
Items: 2048 , time: 79
Items: 4096 , time: 205
Items: 8192 , time: 318
Items: 16384 , time: 744
```

vs

```
// compact
Items: 2 , time: 4
Items: 4 , time: 2
Items: 8 , time: 0
Items: 16 , time: 2
Items: 32 , time: 4
Items: 64 , time: 5
Items: 128 , time: 3
Items: 256 , time: 11
Items: 512 , time: 12
Items: 1024 , time: 27
Items: 2048 , time: 34
Items: 4096 , time: 71
Items: 8192 , time: 156
Items: 16384 , time: 287
```

Guess I need to get my butt in gear and actually figure out how to make the tests pass, huh?

**Comment by gotwarlost** [comment] 2016-06-29 04:34
nice! thanks for looking into this.

**Comment by bcoe** [comment] 2016-06-29 20:48
@gotwarlost is there an action item I can take in `babel-plugin-istanbul` to turn on compact? I saw you were doing some work to expose config options for this I believe?

any other caveats that will bite us as a result of turning on this flag?

**Comment by gotwarlost** [comment] 2016-06-30 01:53
Actually I don't think we can do anything about it since Babel plugins are not responsible for code generation. The user will have to configure this, I think.

The instrumenter API does expose this because it controls the parsing, tree visit and code gen,

If you want me to patch the visitor to unmarshal JSON strings instead, I can do that and we can revert the patch once the perf improvements land in Babel.

**Comment by bcoe** [comment] 2016-06-30 01:56
@gotwarlost sounds like it might make the most sense to keep this open; and get people to play a bit more once we fix that one crashing bug, and the performance fixes land in babel.

I'd also happily do some v8-profiling.

**Comment by hzoo** [comment] 2016-06-30 02:25
@gotwarlost Yeah babel-generator has it's own options, separate from any transform which only transforms an AST that is given to the generator (you should be able to modify certain things through the babelrc)

**Comment by dtinth** [comment] 2016-07-01 05:18
I used `JSON.parse` in my `__coverage__` plugin to work around this performance issue. It also turns out that __in runtime__ creating a JavaScript object using `JSON.parse` is faster than using an object literal.

[Here’s a benchmark that shows that](https://gist.github.com/dtinth/87d79cedb0f56edfb665d65edea03dba). Here’s the result when run in Node v6.0.0.

| items | Embedded literal | Runtime JSON.parse |
| -----:| ----------------:| ------------------:|
| 1 | 0 | 0 |
| 2 | 0 | 0 |
| 4 | 0 | 0 |
| 8 | 0 | 0 |
| 16 | 0 | 0 |
| 32 | 0.1 | 0 |
| 64 | 0.1 | 0.1 |
| 128 | 0.1 | 0.6 |
| 256 | 0.1 | 0.5 |
| 512 | 0.4 | 1.2 |
| 1024 | 1.2 | 2.6 |
| 2048 | 2.8 | 4.4 |
| 4096 | 4.2 | 7.6 |
| 8192 | 11.5 | 15.1 |
| 16384 | 43.1 | 30.8 |
| 32768 | 91.3 | 68.2 |
| 65536 | 151.7 | 130.2 |

**Comment by bcoe** [comment] 2016-07-03 18:48
@dtinth, @gotwarlost interesting, do any tweaks jump out at you that we could make here (if I understand, this is the code where this optimization could be applied? or I'm not quite understanding the benchmark?):

https://github.com/istanbuljs/istanbul-lib-instrument/blob/master/src/visitor.js#L446

**Comment by dtinth** [comment] 2016-07-04 07:27
It’s this line, where `T.valueToNode(coverageData)` is used to turn an initial coverage object into JavaScript AST: https://github.com/istanbuljs/istanbul-lib-instrument/blob/27a0495a3f2d1b627fb0b8955534d483638a68c0/src/visitor.js#L478

This is the kind of code that gets generated by `babel-generate`:

```js
var coverageData = {
  s: {
    "1": 0,
    "2": 0,
    "3": 0,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0
  },
  statementMap: {
    "1": {
      start: {
        line: 1,
        column: 1
      },
      end: {
        line: 1,
        column: 10
      }
    },
    "2": {
      start: {
        line: 1,
        column: 1
      },
      end: {
        line: 1,
        column: 10
      }
    },
    "3": {
      start: {
        line: 1,
        column: 1
      },
      end: {
        line: 1,
        column: 10
      }
    },
    "4": {
      start: {
        line: 1,
        column: 1
      },
      end: {
        line: 1,
        column: 10
      }
    },
    "5": {
      start: {
        line: 1,
        column: 1
      },
      end: {
        line: 1,
        column: 10
      }
    },
    "6": {
      start: {
        line: 1,
        column: 1
      },
      end: {
        line: 1,
        column: 10
      }
    },
    "7": {
      start: {
        line: 1,
        column: 1
      },
      end: {
        line: 1,
        column: 10
      }
    },
    "8": {
      start: {
        line: 1,
        column: 1
      },
      end: {
        line: 1,
        column: 10
      }
    },
    "9": {
      start: {
        line: 1,
        column: 1
      },
      end: {
        line: 1,
        column: 10
      }
    }
  }
}
```

When compact is not turned on, `babel-generate` produces beautiful indentations (which may be the cause of the slowdown). The way I fixed it is by `JSON.stringify`ing the coverage data into the string, and then parse it at runtime.

Instead of using `T.valueToNode(coverageData)`, I used this instead:

```js
T.callExpression(
  T.memberExpression(T.identifier('JSON'), T.identifier('parse')),
  [ T.valueToNode(JSON.stringify(coverageData)) ]
)
```

which generates into this JavaScript code:

```js
var coverageData = JSON.parse("{\"s\":{\"1\":0,\"2\":0,\"3\":0,\"4\":0,\"5\":0,\"6\":0,\"7\":0,\"8\":0,\"9\":0},\"statementMap\":{\"1\":{\"start\":{\"line\":1,\"column\":1},\"end\":{\"line\":1,\"column\":10}},\"2\":{\"start\":{\"line\":1,\"column\":1},\"end\":{\"line\":1,\"column\":10}},\"3\":{\"start\":{\"line\":1,\"column\":1},\"end\":{\"line\":1,\"column\":10}},\"4\":{\"start\":{\"line\":1,\"column\":1},\"end\":{\"line\":1,\"column\":10}},\"5\":{\"start\":{\"line\":1,\"column\":1},\"end\":{\"line\":1,\"column\":10}},\"6\":{\"start\":{\"line\":1,\"column\":1},\"end\":{\"line\":1,\"column\":10}},\"7\":{\"start\":{\"line\":1,\"column\":1},\"end\":{\"line\":1,\"column\":10}},\"8\":{\"start\":{\"line\":1,\"column\":1},\"end\":{\"line\":1,\"column\":10}},\"9\":{\"start\":{\"line\":1,\"column\":1},\"end\":{\"line\":1,\"column\":10}}}}")
```

At runtime, there is an overhead of doing `JSON.parse`, but as shown by a benchmark above, the `JSON.parse` method performs faster during runtime on Node v6.0.0.

**Comment by loganfsmyth** [comment] 2016-07-05 06:15
FYI I've posted https://github.com/babel/babel/pull/3565 which should fix the issues with code generation time on large files.

**Comment by gotwarlost** [comment] 2016-07-05 10:20
@loganfsmyth  Great! Could I also request you to triage this issue with source mappings. It's been sitting in the queue for more than 10 days now.

https://phabricator.babeljs.io/T7453

**Comment by loganfsmyth** [comment] 2016-07-05 14:56
Sure, I can try to take a look tonight.

**Comment by hzoo** [comment] 2016-07-14 12:54
https://github.com/babel/babel/releases/tag/v6.11.3 generator is released with logan's PR

**Comment by gotwarlost** [comment] 2016-07-14 14:37
could we get help with https://phabricator.babeljs.io/T7453 now? :)

**Closed** 2016-07-20 04:56 UTC

**Comment by hzoo** [comment] 2016-08-03 21:54
aside: does someone want to PR babel itself to add the plugin? I'l see if I can do it otherwise

**Comment by bcoe** [comment] 2016-08-03 22:12
@hzoo how does this process work, along with having our own repo for `babel-plugin-istanbul` we'd submit a pull to the plugins folder in `babel/babel`? or would we retire this repo?

**Comment by hzoo** [comment] 2016-08-04 00:38
Oh oops that's a different question. I actually meant if someone wanted to make a PR to use the plugin for babel's own coverage https://github.com/babel/babel/blob/master/package.json#L28-L60.

I think it's cool leaving it here unless yall think it's better under the babel org
