### ISSUE TITLE
object destructuring defaults reported as uncovered branch

### ISSUE THREAD

**Issue by FezVrasta** [istanbuljs/babel-plugin-istanbul#96] opened 2017-03-07 16:59 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The coverage reporter reports that the default values I assign in object destructuring are "not covered branches".

**If the current behavior is a bug, please provide the steps to reproduce and either a repl.it demo through https://repl.it/languages/jest or a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
Simply create a code that uses object destructuring defaults and check out the coverage report:

```
const {
  foo = 'bar'
} = this.props;
```

The `= 'bar'` segment will be considered "uncovered" by the coverage reporter.

**What is the expected behavior?**

The coverage reported will ignore it, since there's nothing to test there.

**Please provide your exact Jest configuration and mention your Jest, node, yarn/npm version and operating system.**

`create-react-app` config reproduces the problem just fine.

Moved from https://github.com/facebook/jest/issues/3091

**Comment by bcoe** [comment] 2017-03-10 04:09
@FezVrasta thanks for the bug report.

In some ways I can see the argument for `= bar` not having been covered; your default values have not been applied (if the this.props contains the keys in question) -- if you wrote a test that provided empty default props `{}`, I believe you would start seeing coverage?

Curious what other folks think? feature or bug? @cpojer, @JaKXz?

**Comment by FezVrasta** [comment] 2017-03-10 07:55
Nope it complains even if in my tests I don't define values and let it use the defaults

**Comment by FezVrasta** [comment] 2017-03-20 19:27
Any news on this? Bug? Feature? I'm doing it wrong?

**Comment by JaKXz** [comment] 2017-03-20 20:32
Based on:

> Nope it complains even if in my tests I don't define values and let it use the defaults

it sounds like a bug to me. I would guess that coverage would be correctly reported if you did the old school way:

```js
const foo = this.props.foo || 'bar'
// Assuming this.props is always defined
```

I'd love to see a failing test in a PR :) but I apologize for the delayed response. I'm not sure exactly where to look off the bat either, but I'll try to do some digging.

**Comment by bcoe** [comment] 2017-05-13 23:52
@FezVrasta I wrote this little test and ran it with the latest Jest:

```js
function a() {
  const {
    foo = 'bar'
  } = this.properties;
}
a.apply({properties: {'foo': 99}})
a.apply({properties: {'bar': 7}})
```

which results in:

```bash
  Buggy test
    ✓ returns true (2ms)

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
 buggy.js |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.994s, estimated 1s
```

I'm pretty sure either the underlying issue has been fixed in recent updates to Istabnul; or your test might not be exercising the case in which the default value is used.

Closing this issue since I couldn't reproduce -- but please feel free to provide a link the the repo that's having this issue (if you're still bumping into it).

**Closed by bcoe** 2017-05-13 23:52 UTC
Labels: enhancement, help wanted

**Comment by mehmetnyarar** [comment] 2020-08-05 09:37
I encounter this issue. My fn:

```ts
export const getConfig = (env?: EnvVars, phase?: string): EnvConfig => {
  const {
    KEY1 = 'default',
    KEY2 = 'default',
    KEY3,
    KEY4,
    KEY5 = 10
  } = env || process.env

  // ...

  return config
}
```

My tests include:

- `getConfig()` without initial env (defaults to process.env)
- `getConfig({})` empty env
- `getConfig({ KEY1: 'value', KEY2: 'value', KEY3: 'value', KEY4: undefined, KEY5: 20 })` with initial env

yet the de-structuring is not covered.

Is there any solution to this? 

> Putting `/* istanbul ignore next */` comment before any de-structuring is not really a solution.

**Comment by akhileshwarr** [comment] 2021-01-05 23:18
I faced same issue while destructuring props,
culprit was react defaultProps, and code will never reach destructuring defaults.

`const {  withCancel = false } = props;  // destructuring defaults are  not reachable

ContentFooter.defaultProps = { // react defaultProps will set the value before it reaches destructuring defaults
  withCancel: false
};`
